# Set color to 256
set -g default-terminal "tmux-256color"

# Start window numbering at 1
set -g base-index 1

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# # Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Use prefix + : for status keys
set -g status-keys emacs

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Vim mode
set-window-option -g mode-keys vi

# Disable paste time
set -g assume-paste-time 0

# Get rid of jumping cursor
set -g repeat-time 0

# Enable mouse for scrolling and other cool stuff.
# Man cannot live in terminal forever.
set -g mouse on

# Easier and faster switching between next/prev window
bind -r C-p previous-window
bind -r C-n next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "nordtheme/tmux"
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @nord_tmux_no_patched_font "1"

# Theme before the Nord theme
# set -g status-bg colour6
# set -g status-fg colour235
# set -g status-style fg=black,bg=cyan
# set -g pane-active-border-style bg=default,fg=cyan
# set -g pane-border-style fg=blue

run '~/.tmux/plugins/tpm/tpm'
